# Site settings
title: Erichain
email: jyamol520@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Created By Erichain.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  Erichain

# Build settings
markdown: kramdown
